version: "3.8"
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - "4000:4000"
    volumes:
      - ./api:/api
      - ./api/node_modules
  app:
    build: ./app
    container_name: app_c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
